version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0-stretch-browsers-legacy
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: ./node_modules/.bin/ng build --prod
      - run:
          command: mkdir public
      - run:
          command: cp -R ./dist/* ./public/
      - run:
          command: npm install --save-dev firebase-tools
      - run:
          command: ./node_modules/.bin/firebase use guillermotti
      - run:
          command: |
            cd functions
            ls
            npm install
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - build
